name: technical_analysis
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  async: ^2.11.0
  collection: ^1.17.2
  fpdart: ^0.6.0
  path: ^1.8.3
  rxdart: ^0.27.7
  statistics: ^1.0.25

dev_dependencies:
  dart_code_metrics: ^5.7.4
  dart_code_metrics_presets: ^1.8.0
  folderslint: ^1.0.3
  lint: ^2.1.2
  test: ^1.24.3
