name: technical_indicators
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  decimal: null
  fpdart: ^0.6.0
  path: ^1.8.0
  rxdart: ^0.27.7

dev_dependencies:
  extra_pedantic: 3.0.0
  lints: ^2.0.0
  test: ^1.21.0
