name: technical_indicators
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  collection: ^1.17.2
  decimal: ^2.3.2
  fpdart: ^0.6.0
  path: ^1.8.3

dev_dependencies:
  dart_code_metrics: ^5.7.3
  dart_code_metrics_presets: ^1.7.0
  lint: ^2.1.2
  test: ^1.24.2
